// components/AppHeader.vue
<template>
	<header>
		<div class="navbar justify-between bg-red-200">
			<!-- Logo -->
			<div>
				<span>Roomerang</span>
			</div>
			<!-- Filter & Search -->
			<div>
				<span>Test</span>
			</div>
			<div class="flex gap-2">
				<button class="btn btn-sm">Rent your house</button>
				<button class="btn btn-sm">
					<Icon name="mingcute:earth-line" />
				</button>
				<button class="btn btn-sm">User account</button>
			</div>
		</div>
	</header>
</template>

// app/components/AppHeader.tsx
function Logo() {
	return (
		<div>
			<span>Roomerang</span>
		</div>
	)
}

function Actions() {
	return (
		<div>
			<button>Rent your house</button>
			<button>World</button>
			<button>User</button>
		</div>
	)
}

export default function AppHeader() {
	return (
		<header className="flex h-20 items-center justify-between">
			<Logo />
			<Actions />
		</header>
	)
}
