// app/components/app-header.tsx
import { Globe } from "lucide-react"
import { Button } from "~/components/ui/button"

function Logo() {
	return (
		<div>
			<span>Roomerang</span>
		</div>
	)
}

function Actions() {
	return (
		<div className="flex items-center">
			<Button variant="ghost">Rent your house</Button>
			<Button variant="ghost">
				<Globe size="20" />
			</Button>
			<button>User</button>
		</div>
	)
}

export default function AppHeader() {
	return (
		<header className="flex h-20 items-center justify-between">
			<Logo />
			<Actions />
		</header>
	)
}

// components/AppHeader.vue
<template>
	<header>
		<div class="navbar justify-between bg-red-200">
			<!-- Logo -->
			<div class="hidden sm:block">
				<span>Roomerang</span>
			</div>
			<!-- Filter & Search -->
			<NavSearch />
			<!-- Actions -->
			<div class="hidden sm:flex">
				<button class="btn-ghost btn-sm btn rounded-full">Rent your house</button>
				<button class="btn-ghost btn-sm btn-circle btn mr-3">
					<Icon name="mingcute:earth-line" />
				</button>
				<button class="btn-outline btn-sm btn h-10 rounded-full">
					<Icon name="mingcute:menu-line" />
					<Icon name="mingcute:user-4-fill" size="2em" />
				</button>
			</div>
		</div>
	</header>
</template>
